
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(lme4)
library(mgcv)
library(mgcViz)
```

```{r}
# set model parameters
auth_type <- "fa"  # fa, la for first or last author
model_type <- "rate"  # rate, count, papers
seed <- 1
gender_interaction <- TRUE  # TRUE, FALSE
load_path <- "./"
fname <- paste("filtered_model_data_by_paper_", auth_type, sep="")

# load dataframe and make certain columns factors
df <- read.csv( file.path(load_path, paste(fname, ".csv", sep="")) )
factor_col_names <- c('field', 'affil_continent', 'gender', 'affil_lmic', 'author_number', 
                      'document_type')
df <- df %>% 
  mutate(across(all_of(factor_col_names), as.factor))
head(df)

# set reference levels
df$affil_continent <- relevel(df$affil_continent, ref="Asia")
df$field <- relevel(df$field, ref="Psychiatry")
df$document_type <- relevel(df$document_type, ref="Article")
# df$affil_lmic <- relevel(df$affil_lmic, ref=0)


print(nrow(df))
print(length(unique(df$author_number)))

# subset one per author
set.seed(seed)
df <- df %>%
  group_by(author_number) %>%
  sample_n(1)

print(nrow(df))
print(length(unique(df$author_number)))

head(df)




```


```{r}
# different num of basis function for fa/la

if (gender_interaction==FALSE) {
  if ((auth_type=="fa") & (model_type=="count")) {
    fit_gam <- gam(sc_count ~ s(num_prev_papers, k=20)  + s(academic_age, k=20) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )
  
  } else if ((auth_type=="la") & (model_type=="count")) {
    fit_gam <- gam(sc_count ~ s(num_prev_papers, k=20)  + s(academic_age, k=20) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=12) + s(journal_citing_if, k=15) + 
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )  
  } else if ((auth_type=="fa") & (model_type=="rate")) {
    fit_gam <- gam(sc_rate ~ s(num_prev_papers, k=20)  + s(academic_age, k=20) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )  
    
  } else if ((auth_type=="la") & (model_type=="rate")) {
    fit_gam <- gam(sc_rate ~ s(num_prev_papers, k=20)  + s(academic_age, k=20) + s(year_citing, k=15) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )   
    
  }  else if (model_type=="papers") {
    fit_gam <- gam(num_prev_papers ~ s(academic_age, k=10) + s(year_citing, k=10) + s(journal_citing_if, k=10) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )
    
  }
} else if (gender_interaction==TRUE) {
  if ((auth_type=="fa") & (model_type=="count")) {
    fit_gam <- gam(sc_count ~ s(num_prev_papers, k=20, by=gender)  + s(academic_age, k=20, by=gender) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )
  
  } else if ((auth_type=="la") & (model_type=="count")) {
    fit_gam <- gam(sc_count ~ s(num_prev_papers, k=20, by=gender)  + s(academic_age, k=20, by=gender) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=12) + s(journal_citing_if, k=15) + 
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )  
  } else if ((auth_type=="fa") & (model_type=="rate")) {
    fit_gam <- gam(sc_rate ~ s(num_prev_papers, k=20, by=gender)  + s(academic_age, k=20, by=gender) + s(year_citing, k=10) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )  
    
  } else if ((auth_type=="la") & (model_type=="rate")) {
    fit_gam <- gam(sc_rate ~ s(num_prev_papers, k=20, by=gender)  + s(academic_age, k=20, by=gender) + s(year_citing, k=15) + s(timelag, k=20) +
                            s(num_auth_citing, k=20) + s(num_ref, k=20) + s(journal_citing_if, k=20) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )   
    
  }  else if (model_type=="papers") {
    fit_gam <- gam(num_prev_papers ~ s(academic_age, k=10, by=gender) + s(year_citing, k=10) + s(journal_citing_if, k=10) +
                            field + gender + affil_lmic + document_type,
                          data = df,
                          family=Tweedie(p=1.2),
                          samfrac = 1
    
                          )
    
  }
}


fit_gam_summary <- summary(fit_gam)
fit_gam_summary
concurvity(fit_gam)
gam.check(fit_gam)
```



```{r}

b <- getViz(fit_gam)
if (model_type!="papers"){
  print(plot(b, allTerms=T, select=1:7, xlab=c('a', 'b', 'c', 'd', 'e', 'f', 'g')), page=1)
  
  print(plot(b, allTerms=T, select=8:11), page=1)
} else {
  print(plot(b, allTerms=T, select=1:3), page=1)
  print(plot(b, allTerms=T, select=4:7), page=1)
  
}
```


